import { Tile, TileType, PropertyColor, Card, CardEffect } from './types.js';

// ============================================================
// BOARD DATA — 40 ô bàn cờ Cờ Tỷ Phú Việt Nam
// Đơn vị: VNĐ (dùng số nguyên, không rút gọn triệu)
// ============================================================

// Ghi chú rent[]: [0 nhà, 1 nhà, 2 nhà, 3 nhà, 4 nhà, khách sạn]
// Bến xe rent[]:  [1 bến, 2 bến, 3 bến, 4 bến]
// Tiện ích:       thu = hệ số × tổng xúc xắc (4x nếu 1 tiện ích, 10x nếu độc quyền 2)

const M = 1_000_000; // 1 triệu

export const BOARD_TILES: Tile[] = [
  // ── DƯỚI (phải → trái, index 0-9) ──────────────────────
  {
    index: 0,
    name: 'Xuất Phát',
    type: TileType.GO,
    image: 'corners/go.png',
  },
  {
    index: 1,
    name: 'Hà Nội',
    type: TileType.PROPERTY,
    color: PropertyColor.BROWN,
    price: 1.2 * M,
    housePrice: 1 * M,
    hotelPrice: 1 * M,
    rent: [0.1 * M, 0.4 * M, 0.8 * M, 1.6 * M, 2.0 * M, 4.0 * M],
    image: 'properties/ha-noi.png',
  },
  {
    index: 2,
    name: 'Khí Vận',
    type: TileType.COMMUNITY,
    image: 'cards/khi-van-back.png',
  },
  {
    index: 3,
    name: 'Hải Dương',
    type: TileType.PROPERTY,
    color: PropertyColor.BROWN,
    price: 1.4 * M,
    housePrice: 1 * M,
    hotelPrice: 1 * M,
    rent: [0.12 * M, 0.5 * M, 1.0 * M, 2.0 * M, 2.5 * M, 5.0 * M],
    image: 'properties/hai-duong.png',
  },
  {
    index: 4,
    name: 'Thuế Thu Nhập',
    type: TileType.TAX,
    taxAmount: 1.5 * M,
    image: 'ui/tax-income.png',
  },
  {
    index: 5,
    name: 'Bến Xe Hà Nội',
    type: TileType.STATION,
    price: 2.5 * M,
    rent: [0.5 * M, 1.0 * M, 2.0 * M, 4.0 * M],
    image: 'specials/ben-xe-ha-noi.png',
  },
  {
    index: 6,
    name: 'Hải Phòng',
    type: TileType.PROPERTY,
    color: PropertyColor.LIGHT_BLUE,
    price: 1.8 * M,
    housePrice: 1.5 * M,
    hotelPrice: 1.5 * M,
    rent: [0.15 * M, 0.6 * M, 1.2 * M, 2.4 * M, 3.0 * M, 6.0 * M],
    image: 'properties/hai-phong.png',
  },
  {
    index: 7,
    name: 'Cơ Hội',
    type: TileType.CHANCE,
    image: 'cards/co-hoi-back.png',
  },
  {
    index: 8,
    name: 'Quảng Ninh',
    type: TileType.PROPERTY,
    color: PropertyColor.LIGHT_BLUE,
    price: 1.9 * M,
    housePrice: 1.5 * M,
    hotelPrice: 1.5 * M,
    rent: [0.16 * M, 0.65 * M, 1.3 * M, 2.6 * M, 3.2 * M, 6.5 * M],
    image: 'properties/quang-ninh.png',
  },
  {
    index: 9,
    name: 'Lạng Sơn',
    type: TileType.PROPERTY,
    color: PropertyColor.LIGHT_BLUE,
    price: 2.0 * M,
    housePrice: 1.5 * M,
    hotelPrice: 1.5 * M,
    rent: [0.18 * M, 0.7 * M, 1.4 * M, 2.8 * M, 3.5 * M, 7.0 * M],
    image: 'properties/lang-son.png',
  },

  // ── GÓC TRÁI DƯỚI (index 10) ───────────────────────────
  {
    index: 10,
    name: 'Thăm Tù',
    type: TileType.JAIL,
    image: 'corners/jail.png',
  },

  // ── TRÁI (dưới → trên, index 11-19) ────────────────────
  {
    index: 11,
    name: 'Thanh Hóa',
    type: TileType.PROPERTY,
    color: PropertyColor.PINK,
    price: 2.6 * M,
    housePrice: 2 * M,
    hotelPrice: 2 * M,
    rent: [0.22 * M, 0.9 * M, 1.8 * M, 3.6 * M, 4.5 * M, 9.0 * M],
    image: 'properties/thanh-hoa.png',
  },
  {
    index: 12,
    name: 'Công Ty Điện',
    type: TileType.UTILITY,
    price: 3.0 * M,
    image: 'specials/cong-ty-dien.png',
  },
  {
    index: 13,
    name: 'Nghệ An',
    type: TileType.PROPERTY,
    color: PropertyColor.PINK,
    price: 2.8 * M,
    housePrice: 2 * M,
    hotelPrice: 2 * M,
    rent: [0.24 * M, 1.0 * M, 2.0 * M, 4.0 * M, 5.0 * M, 10 * M],
    image: 'properties/nghe-an.png',
  },
  {
    index: 14,
    name: 'Khí Vận',
    type: TileType.COMMUNITY,
    image: 'cards/khi-van-back.png',
  },
  {
    index: 15,
    name: 'Bến Xe Miền Trung',
    type: TileType.STATION,
    price: 2.5 * M,
    rent: [0.5 * M, 1.0 * M, 2.0 * M, 4.0 * M],
    image: 'specials/ben-xe-mien-trung.png',
  },
  {
    index: 16,
    name: 'Huế',
    type: TileType.PROPERTY,
    color: PropertyColor.PINK,
    price: 3.0 * M,
    housePrice: 2 * M,
    hotelPrice: 2 * M,
    rent: [0.26 * M, 1.1 * M, 2.2 * M, 4.4 * M, 5.5 * M, 11 * M],
    image: 'properties/hue.png',
  },
  {
    index: 17,
    name: 'Cơ Hội',
    type: TileType.CHANCE,
    image: 'cards/co-hoi-back.png',
  },
  {
    index: 18,
    name: 'Đà Nẵng',
    type: TileType.PROPERTY,
    color: PropertyColor.ORANGE,
    price: 3.2 * M,
    housePrice: 2.5 * M,
    hotelPrice: 2.5 * M,
    rent: [0.28 * M, 1.2 * M, 2.4 * M, 4.8 * M, 6.0 * M, 12 * M],
    image: 'properties/da-nang.png',
  },
  {
    index: 19,
    name: 'Quảng Nam',
    type: TileType.PROPERTY,
    color: PropertyColor.ORANGE,
    price: 3.4 * M,
    housePrice: 2.5 * M,
    hotelPrice: 2.5 * M,
    rent: [0.3 * M, 1.3 * M, 2.6 * M, 5.2 * M, 6.5 * M, 13 * M],
    image: 'properties/quang-nam.png',
  },

  // ── GÓC TRÁI TRÊN (index 20) ──────────────────────────
  {
    index: 20,
    name: 'Đỗ Xe',
    type: TileType.FREE_PARKING,
    image: 'corners/free-parking.png',
  },

  // ── TRÊN (trái → phải, index 21-29) ────────────────────
  {
    index: 21,
    name: 'Quảng Ngãi',
    type: TileType.PROPERTY,
    color: PropertyColor.ORANGE,
    price: 3.6 * M,
    housePrice: 2.5 * M,
    hotelPrice: 2.5 * M,
    rent: [0.32 * M, 1.4 * M, 2.8 * M, 5.6 * M, 7.0 * M, 14 * M],
    image: 'properties/quang-ngai.png',
  },
  {
    index: 22,
    name: 'Khí Vận',
    type: TileType.COMMUNITY,
    image: 'cards/khi-van-back.png',
  },
  {
    index: 23,
    name: 'Bình Định',
    type: TileType.PROPERTY,
    color: PropertyColor.RED,
    price: 4.0 * M,
    housePrice: 3 * M,
    hotelPrice: 3 * M,
    rent: [0.36 * M, 1.6 * M, 3.2 * M, 6.4 * M, 8.0 * M, 16 * M],
    image: 'properties/binh-dinh.png',
  },
  {
    index: 24,
    name: 'Nha Trang',
    type: TileType.PROPERTY,
    color: PropertyColor.RED,
    price: 4.2 * M,
    housePrice: 3 * M,
    hotelPrice: 3 * M,
    rent: [0.38 * M, 1.7 * M, 3.4 * M, 6.8 * M, 8.5 * M, 17 * M],
    image: 'properties/nha-trang.png',
  },
  {
    index: 25,
    name: 'Bến Xe Miền Nam',
    type: TileType.STATION,
    price: 2.5 * M,
    rent: [0.5 * M, 1.0 * M, 2.0 * M, 4.0 * M],
    image: 'specials/ben-xe-mien-nam.png',
  },
  {
    index: 26,
    name: 'Đà Lạt',
    type: TileType.PROPERTY,
    color: PropertyColor.RED,
    price: 4.4 * M,
    housePrice: 3 * M,
    hotelPrice: 3 * M,
    rent: [0.4 * M, 1.8 * M, 3.6 * M, 7.2 * M, 9.0 * M, 18 * M],
    image: 'properties/da-lat.png',
  },
  {
    index: 27,
    name: 'Cơ Hội',
    type: TileType.CHANCE,
    image: 'cards/co-hoi-back.png',
  },
  {
    index: 28,
    name: 'Vũng Tàu',
    type: TileType.PROPERTY,
    color: PropertyColor.YELLOW,
    price: 4.8 * M,
    housePrice: 3.5 * M,
    hotelPrice: 3.5 * M,
    rent: [0.44 * M, 2.0 * M, 4.0 * M, 8.0 * M, 10 * M, 20 * M],
    image: 'properties/vung-tau.png',
  },
  {
    index: 29,
    name: 'Bình Dương',
    type: TileType.PROPERTY,
    color: PropertyColor.YELLOW,
    price: 5.0 * M,
    housePrice: 3.5 * M,
    hotelPrice: 3.5 * M,
    rent: [0.46 * M, 2.1 * M, 4.2 * M, 8.4 * M, 10.5 * M, 21 * M],
    image: 'properties/binh-duong.png',
  },

  // ── GÓC PHẢI TRÊN (index 30) ──────────────────────────
  {
    index: 30,
    name: 'Vào Tù',
    type: TileType.GO_TO_JAIL,
    image: 'corners/go-to-jail.png',
  },

  // ── PHẢI (trên → dưới, index 31-39) ─────────────────────
  {
    index: 31,
    name: 'Đồng Nai',
    type: TileType.PROPERTY,
    color: PropertyColor.YELLOW,
    price: 5.2 * M,
    housePrice: 3.5 * M,
    hotelPrice: 3.5 * M,
    rent: [0.48 * M, 2.2 * M, 4.4 * M, 8.8 * M, 11 * M, 22 * M],
    image: 'properties/dong-nai.png',
  },
  {
    index: 32,
    name: 'Công Ty Nước',
    type: TileType.UTILITY,
    price: 3.0 * M,
    image: 'specials/cong-ty-nuoc.png',
  },
  {
    index: 33,
    name: 'Cần Thơ',
    type: TileType.PROPERTY,
    color: PropertyColor.GREEN,
    price: 5.6 * M,
    housePrice: 4 * M,
    hotelPrice: 4 * M,
    rent: [0.5 * M, 2.4 * M, 4.8 * M, 9.6 * M, 12 * M, 24 * M],
    image: 'properties/can-tho.png',
  },
  {
    index: 34,
    name: 'Thuế Sang Trọng',
    type: TileType.TAX,
    taxAmount: 2.0 * M,
    image: 'ui/tax-luxury.png',
  },
  {
    index: 35,
    name: 'Sân Bay Tân Sơn Nhất',
    type: TileType.STATION,
    price: 2.5 * M,
    rent: [0.5 * M, 1.0 * M, 2.0 * M, 4.0 * M],
    image: 'specials/san-bay-tsn.png',
  },
  {
    index: 36,
    name: 'Long An',
    type: TileType.PROPERTY,
    color: PropertyColor.GREEN,
    price: 6.0 * M,
    housePrice: 4 * M,
    hotelPrice: 4 * M,
    rent: [0.54 * M, 2.6 * M, 5.2 * M, 10.4 * M, 13 * M, 26 * M],
    image: 'properties/long-an.png',
  },
  {
    index: 37,
    name: 'Khí Vận',
    type: TileType.COMMUNITY,
    image: 'cards/khi-van-back.png',
  },
  {
    index: 38,
    name: 'TP. Hồ Chí Minh',
    type: TileType.PROPERTY,
    color: PropertyColor.DARK_BLUE,
    price: 7.0 * M,
    housePrice: 5 * M,
    hotelPrice: 5 * M,
    rent: [0.7 * M, 3.5 * M, 7.0 * M, 14 * M, 17.5 * M, 35 * M],
    image: 'properties/ho-chi-minh.png',
  },
  {
    index: 39,
    name: 'Phú Quốc',
    type: TileType.PROPERTY,
    color: PropertyColor.DARK_BLUE,
    price: 8.0 * M,
    housePrice: 5 * M,
    hotelPrice: 5 * M,
    rent: [1.0 * M, 5.0 * M, 10 * M, 20 * M, 25 * M, 50 * M],
    image: 'properties/phu-quoc.png',
  },
];

// ── Nhóm màu → danh sách ô ─────────────────────────────────
export const COLOR_GROUPS: Record<PropertyColor, number[]> = {
  [PropertyColor.BROWN]: [1, 3],
  [PropertyColor.LIGHT_BLUE]: [6, 8, 9],
  [PropertyColor.PINK]: [11, 13, 16],
  [PropertyColor.ORANGE]: [18, 19, 21],
  [PropertyColor.RED]: [23, 24, 26],
  [PropertyColor.YELLOW]: [28, 29, 31],
  [PropertyColor.GREEN]: [33, 36],
  [PropertyColor.DARK_BLUE]: [38, 39],
};

export const STATION_INDICES = [5, 15, 25, 35];
export const UTILITY_INDICES = [12, 32];

// ── Thẻ Cơ Hội (16 thẻ) ───────────────────────────────────
export const CHANCE_CARDS: Card[] = [
  {
    id: 'ch1',
    type: 'chance',
    text: 'Tiến đến ô Xuất Phát. Nhận 2 triệu tiền lương.',
    effect: CardEffect.MOVE_TO,
    value: 0,
  },
  {
    id: 'ch2',
    type: 'chance',
    text: 'Tiến đến Phú Quốc. Nếu qua Xuất Phát, nhận 2 triệu.',
    effect: CardEffect.MOVE_TO,
    value: 39,
  },
  {
    id: 'ch3',
    type: 'chance',
    text: 'Tiến đến Sân Bay Tân Sơn Nhất. Nếu qua Xuất Phát, nhận 2 triệu.',
    effect: CardEffect.MOVE_TO,
    value: 35,
  },
  {
    id: 'ch4',
    type: 'chance',
    text: 'Ngân hàng trả cổ tức cho bạn. Nhận 1 triệu.',
    effect: CardEffect.COLLECT,
    value: 1 * M,
  },
  {
    id: 'ch5',
    type: 'chance',
    text: 'Thẻ thoát tù miễn phí. Giữ thẻ này cho đến khi cần.',
    effect: CardEffect.GET_OUT_OF_JAIL,
  },
  {
    id: 'ch6',
    type: 'chance',
    text: 'Lùi 3 bước.',
    effect: CardEffect.MOVE_BACK,
    value: 3,
  },
  {
    id: 'ch7',
    type: 'chance',
    text: 'Vào tù ngay lập tức. Không được nhận lương qua Xuất Phát.',
    effect: CardEffect.GO_TO_JAIL,
  },
  {
    id: 'ch8',
    type: 'chance',
    text: 'Sửa chữa bất động sản: nộp 1.5 triệu mỗi nhà, 5 triệu mỗi khách sạn.',
    effect: CardEffect.HOUSE_HOTEL_TAX,
    perHouse: 1.5 * M,
    perHotel: 5 * M,
  },
  {
    id: 'ch9',
    type: 'chance',
    text: 'Bị phạt vượt đèn đỏ. Trả 1 triệu cho ngân hàng.',
    effect: CardEffect.PAY,
    value: 1 * M,
  },
  {
    id: 'ch10',
    type: 'chance',
    text: 'Bạn được bầu làm Chủ tịch Hội đồng quản trị. Trả mỗi người chơi 500 nghìn.',
    effect: CardEffect.PAY_TO_PLAYERS,
    value: 0.5 * M,
  },
  {
    id: 'ch11',
    type: 'chance',
    text: 'Tiến đến Bến Tàu gần nhất. Nếu chưa có chủ, bạn có thể mua. Nếu có chủ, trả gấp đôi tiền thuê.',
    effect: CardEffect.MOVE_TO_NEAREST_STATION,
  },
  {
    id: 'ch12',
    type: 'chance',
    text: 'Tiến đến Bến Tàu gần nhất. Nếu chưa có chủ, bạn có thể mua. Nếu có chủ, trả gấp đôi tiền thuê.',
    effect: CardEffect.MOVE_TO_NEAREST_STATION,
  },
  {
    id: 'ch13',
    type: 'chance',
    text: 'Tiến đến Công ty Điện/Nước gần nhất. Nếu chưa có chủ, bạn có thể mua. Nếu có chủ, trả xúc xắc × 10.',
    effect: CardEffect.MOVE_TO_NEAREST_UTILITY,
  },
  {
    id: 'ch14',
    type: 'chance',
    text: 'Trái phiếu đầu tư đáo hạn. Nhận 1.5 triệu từ ngân hàng.',
    effect: CardEffect.COLLECT,
    value: 1.5 * M,
  },
  {
    id: 'ch15',
    type: 'chance',
    text: 'Bị phạt vì chạy quá tốc độ. Trả 500 nghìn cho ngân hàng.',
    effect: CardEffect.PAY,
    value: 0.5 * M,
  },
  {
    id: 'ch16',
    type: 'chance',
    text: 'Tiến đến Hồ Hoàn Kiếm. Nếu qua Xuất Phát, nhận 2 triệu.',
    effect: CardEffect.MOVE_TO,
    value: 24,
  },
];

// ── Thẻ Khí Vận (16 thẻ) ───────────────────────────────────
export const COMMUNITY_CARDS: Card[] = [
  {
    id: 'kv1',
    type: 'community',
    text: 'Tiến đến ô Xuất Phát. Nhận 2 triệu tiền lương.',
    effect: CardEffect.MOVE_TO,
    value: 0,
  },
  {
    id: 'kv2',
    type: 'community',
    text: 'Nhận tiền thừa kế: 2 triệu.',
    effect: CardEffect.COLLECT,
    value: 2 * M,
  },
  {
    id: 'kv3',
    type: 'community',
    text: 'Hoàn thuế thu nhập. Nhận 500 nghìn.',
    effect: CardEffect.COLLECT,
    value: 0.5 * M,
  },
  {
    id: 'kv4',
    type: 'community',
    text: 'Thẻ thoát tù miễn phí. Giữ thẻ này cho đến khi cần.',
    effect: CardEffect.GET_OUT_OF_JAIL,
  },
  {
    id: 'kv5',
    type: 'community',
    text: 'Vào tù ngay lập tức. Không được nhận lương qua Xuất Phát.',
    effect: CardEffect.GO_TO_JAIL,
  },
  {
    id: 'kv6',
    type: 'community',
    text: 'Ngày sinh nhật của bạn! Mỗi người chơi tặng bạn 500 nghìn.',
    effect: CardEffect.COLLECT_FROM_PLAYERS,
    value: 0.5 * M,
  },
  {
    id: 'kv7',
    type: 'community',
    text: 'Phí bảo hiểm y tế. Trả 1.5 triệu cho ngân hàng.',
    effect: CardEffect.PAY,
    value: 1.5 * M,
  },
  {
    id: 'kv8',
    type: 'community',
    text: 'Bán cổ phiếu được lãi. Nhận 1 triệu.',
    effect: CardEffect.COLLECT,
    value: 1 * M,
  },
  {
    id: 'kv9',
    type: 'community',
    text: 'Phí sửa chữa đường phố: nộp 1 triệu mỗi nhà, 4 triệu mỗi khách sạn.',
    effect: CardEffect.HOUSE_HOTEL_TAX,
    perHouse: 1 * M,
    perHotel: 4 * M,
  },
  {
    id: 'kv10',
    type: 'community',
    text: 'Giải thưởng cuộc thi sắc đẹp hoa hậu. Nhận 1.5 triệu.',
    effect: CardEffect.COLLECT,
    value: 1.5 * M,
  },
  {
    id: 'kv11',
    type: 'community',
    text: 'Ngân hàng nhầm lẫn có lợi cho bạn. Nhận 2 triệu.',
    effect: CardEffect.COLLECT,
    value: 2 * M,
  },
  {
    id: 'kv12',
    type: 'community',
    text: 'Đóng học phí. Trả 500 nghìn cho ngân hàng.',
    effect: CardEffect.PAY,
    value: 0.5 * M,
  },
  {
    id: 'kv13',
    type: 'community',
    text: 'Bảo hiểm nhân thọ đáo hạn. Nhận 1 triệu.',
    effect: CardEffect.COLLECT,
    value: 1 * M,
  },
  {
    id: 'kv14',
    type: 'community',
    text: 'Nhận tiền cho thuê căn hộ cũ. Nhận 500 nghìn.',
    effect: CardEffect.COLLECT,
    value: 0.5 * M,
  },
  {
    id: 'kv15',
    type: 'community',
    text: 'Tư vấn và dịch vụ chuyên nghiệp. Trả 500 nghìn cho ngân hàng.',
    effect: CardEffect.PAY,
    value: 0.5 * M,
  },
  {
    id: 'kv16',
    type: 'community',
    text: 'Bạn giành được giải xổ số. Nhận 1 triệu từ mỗi người chơi.',
    effect: CardEffect.COLLECT_FROM_PLAYERS,
    value: 1 * M,
  },
];
